version: "2.2"

services:
  webknossos:
    image: scalableminds/webknossos:${DOCKER_TAG:-master}
    ports:
      - "127.0.0.1:9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
      fossildb:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      - -Dconfig.file=conf/application.conf
      - -Djava.net.preferIPv4Stack=true
      - -Dhttp.address=0.0.0.0
      - -Dtracingstore.fossildb.address=fossildb
      - -Dtracingstore.redis.address=redis
      - -Dslick.db.url=jdbc:postgresql://postgres/webknossos
      - -Dapplication.insertInitialData=false
      - -Dapplication.authentication.enableDevAutoLogin=false
      - -Dhttp.uri=https://${PUBLIC_HOST}
      - -Dtracingstore.publicUri=https://${PUBLIC_HOST}
      - -Ddatastore.publicUri=https://${PUBLIC_HOST}

    volumes:
#      - ./data:/srv/webknossos/binaryData
#      -  /media/data_cifs/pbtest:/srv/webknossos/binaryData/pbtest/
#      -  /media/data_cifs:/media/data_cifs
      -  /webknossos/pbtest:/srv/webknossos/binaryData/pbtest/
      -  /webknossos:/webknossos
      -  ./webknossos/application.conf:/srv/webknossos/conf/application.conf
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres/webknossos
      - VIRTUAL_HOST=${PUBLIC_HOST}
      - LETSENCRYPT_HOST=${PUBLIC_HOST}
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    restart: unless-stopped

  # Postgres
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: webknossos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1 -p 5432"]
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./persistent/postgres:/var/lib/postgresql/data/"
    restart: unless-stopped

  psql:
    extends: postgres
    command: psql -h postgres -U postgres webknossos
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres

  # FossilDB
  fossildb:
    image: scalableminds/fossildb:master__410
    command:
      - fossildb
      - -c
      - skeletons,skeletonUpdates,volumes,volumeData,volumeUpdates
    user: 0:0
    volumes:
      - "./persistent/fossildb/data:/fossildb/data"
      - "./persistent/fossildb/backup:/fossildb/backup"
    restart: unless-stopped

  # Redis
  redis:
    image: redis:5.0
    command:
      - redis-server
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - "exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG"
      timeout: 1s
      interval: 5s
      retries: 10
    restart: unless-stopped

  # Nginx
  nginx:
    image: scalableminds/nginx-proxy:master__117
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./persistent/nginx/certs:/etc/nginx/certs
      - ./persistent/nginx/vhost.d:/etc/nginx/vhost.d
      - ./persistent/nginx/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./persistent/nginx/certs:/etc/nginx/certs
      - ./persistent/nginx/vhost.d:/etc/nginx/vhost.d
      - ./persistent/nginx/html:/usr/share/nginx/html

  brown-nginx_ms:
    image: really/nginx-modsecurity
    container_name: production_nginx_ms
    volumes:
      - ./nginx_ms/conf.d:/etc/nginx/conf.d:rw
      - ./nginx_ms/html:/etc/nginx/html:rw
      - ./nginx_ms/connectomics.clps.brown.edu.crt:/etc/ssl/certs/connectomics.clps.brown.edu.crt
      - ./nginx_ms:/etc/ssl/certs
      - ./nginx_ms:/etc/ssl/private
      - ./nginx_ms/connectomics.clps.brown.edu.key:/etc/ssl/private/connectomics.clps.brown.edu.key
      - ./nginx_ms/modsec/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/usr/local/owasp-modsecurity-crs-3.0.0/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:rw
    ports:
      - 443:443
    restart: unless-stopped

  brown-sumo:
    image: sumologic/collector:latest
    container_name: production_sumo
    environment:
      - SUMO_SOURCES_JSON=/sumo/sources.json
      - SUMO_COLLECTOR_HOSTNAME=connectomics.clps.brown.edu
      - SUMO_ACCESS_ID=suwpM2KrJg4alA
      - SUMO_ACCESS_KEY=NlyxD1rEGLw7oFAKdv1FIWV8fByLfzEb4EWJOskqiuFdvbQvmsGRIHqsmknytF5Z
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /data/webknossos/sumo:/sumo
    restart: unless-stopped

  brown-sync:
    build:
      context: ./
      dockerfile: Dockerfile_sync
    container_name: production_brown_sync
    volumes:
      - /media/data_cifs:/src
      - /webknossos:/dest
      - ./run.sh:/script/run.sh
    restart: unless-stopped
      
